export const FETCH_REC_LOADING = "FETCH_REC_LOADING";
export const FETCH_REC_SUCCESS = "FETCH_REC_SUCCESS";
export const FETCH_REC_ERROR   = "FETCH_REC_ERROR";

export const FETCH_PDF_LOADING = "FETCH_PDF_LOADING";
export const FETCH_PDF_SUCCESS = "FETCH_PDF_SUCCESS";
export const FETCH_PDF_ERROR   = "FETCH_PDF_ERROR";