version: "3.8"
services:
  fastapi:
    container_name: fastapi
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - "jointops"
  # !React app currently down.
  # react:
  #   container_name: react
  #   build:
  #     context: dashboard
  #     dockerfile: Docker-ui/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - "jointops"
  elasticsearch-1:
    container_name: elasticsearch-1
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "jointops"
  kibana:
    container_name: kibana
    image: "docker.elastic.co/kibana/kibana:7.12.0"
    ports:
      - "5601:5601"
    networks:
      - "jointops"
networks:
  jointops:
